service:
  name: hello-bot

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-mocha-plugin
  - serverless-plugin-export-endpoints

package:
  include:
    - mocks/**/*.json
  exclude:
    - "test/**/*"

provider:
  name: aws
  runtime: nodejs12.x
  versionFunctions: false
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-2'}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
      Resource:
        - "arn:aws:logs:*:*:*"
  timeout: 30
  environment:
    env_name: ${self:provider.stage}
    slackSecret: ${self:custom.env.slackSecret, ''}
  logs:
    restApi: true

custom:
  env: ${file(env/${self:provider.stage}-${self:provider.region}.yml)}
  serverless-offline:
    port: 8000

functions:
  helloBot:
    handler: src/helloBot/botController.main
    events:
      - http:
          method: post
          path: helloBot
          authorizer: ${self:custom.env.api-gateway-authorizer, ''}